const fallbackDestinations = [
  {
    name: 'Ziro Valley',
    state: 'Arunachal Pradesh',
    region: 'Northeast',
    tag: 'Hidden Gem',
    emoji: 'Peak',
    image: '/images/ziro_valley_1777233795515.png',
    rating: 4.9,
    reviews: 128,
    difficulty: 'Moderate',
    bestSeason: 'Sep-Nov',
    duration: '3-5 days',
    description: 'Ancient tribal culture amid misty pine forests. Home to the Apatani tribe and a UNESCO World Heritage nominee.',
    tips: ['Carry warm clothes even in summer', 'Visit during Ziro Music Festival in September', 'Homestays are the best way to experience local culture'],
    activities: ['Trekking', 'Bird Watching', 'Cultural Tours', 'Photography'],
    budgetMin: 8000,
    budgetMax: 15000,
    contributorName: 'Rahul D.',
    isVerified: true,
  },
  {
    name: 'Chopta',
    state: 'Uttarakhand',
    region: 'North India',
    tag: 'Remote',
    emoji: 'Hill',
    image: '/images/chopta_1777233813934.png',
    rating: 4.8,
    reviews: 94,
    difficulty: 'Easy-Moderate',
    bestSeason: 'Mar-Jun',
    duration: '2-3 days',
    description: 'Mini Switzerland of India. A hidden meadow at 2,680m perfect for camping, with views of Tungnath temple and Chandrashila peak.',
    tips: ['Road closes in heavy winter snow', 'Tungnath is the highest Shiva temple in the world', 'Start Chandrashila trek by 5 AM for best views'],
    activities: ['Camping', 'Trekking', 'Temple Visit', 'Stargazing'],
    budgetMin: 5000,
    budgetMax: 10000,
    contributorName: 'Priya S.',
    isVerified: true,
  },
  {
    name: 'Dzukou Valley',
    state: 'Nagaland',
    region: 'Northeast',
    tag: 'Offbeat',
    emoji: 'Bloom',
    image: '/images/dzukou_valley.png',
    rating: 4.7,
    reviews: 56,
    difficulty: 'Moderate-Hard',
    bestSeason: 'Jun-Sep',
    duration: '2-4 days',
    description: 'Valley of flowers on the roof of the Northeast. Seasonal flowers bloom across rolling hills with no commercial development.',
    tips: ['Two base camps - Viswema and Zakhama', 'Carry all supplies, no shops in valley', 'Dzukou lily blooms only in June-July'],
    activities: ['Trekking', 'Camping', 'Photography', 'Nature Walks'],
    budgetMin: 6000,
    budgetMax: 12000,
    contributorName: 'Ananya K.',
    isVerified: true,
  },
  {
    name: 'Tirthan Valley',
    state: 'Himachal Pradesh',
    region: 'North India',
    tag: 'Local Pick',
    emoji: 'River',
    image: '/images/tirthan_valley.png',
    rating: 4.9,
    reviews: 143,
    difficulty: 'Easy',
    bestSeason: 'Apr-Jun, Sep-Nov',
    duration: '3-5 days',
    description: 'Crystal rivers and zero crowds. One of Himachal\'s best-kept secrets near Great Himalayan National Park.',
    tips: ['Permits needed for GHNP entry', 'Trout fishing available with local guides', 'Serolsar Lake trek is hidden gem inside GHNP'],
    activities: ['Fishing', 'Hiking', 'Wildlife Spotting', 'River Crossing'],
    budgetMin: 7000,
    budgetMax: 14000,
    contributorName: 'Mohan T.',
    isVerified: true,
  },
  {
    name: 'Puri',
    state: 'Odisha',
    region: 'East India',
    tag: 'Local Pick',
    emoji: 'Temple',
    image: '/images/puri_odisha_1777233725290.png',
    rating: 4.9,
    reviews: 320,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '2-4 days',
    description: 'The sacred coastal town of Lord Jagannath, offering divine tranquility, ancient history, and beautiful beaches.',
    tips: ['Visit the temple early morning to avoid crowds', 'Enjoy the Golden Beach at sunset', 'Try the local Mahaprasad'],
    activities: ['Temple Visit', 'Beach Walk', 'Cultural Tours', 'Surfing'],
    budgetMin: 4000,
    budgetMax: 10000,
    contributorName: 'Debashis R.',
    isVerified: true,
  },
  {
    name: 'Bhubaneswar',
    state: 'Odisha',
    region: 'East India',
    tag: 'Hidden Gem',
    emoji: 'City',
    image: '/images/bhubaneswar_1777233740502.png',
    rating: 4.8,
    reviews: 210,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '2-3 days',
    description: 'An ancient city blending thousands of intricate sandstone temples with modern life, known as the Temple City of India.',
    tips: ['Lingaraj Temple is a must-visit', 'Explore the Udayagiri and Khandagiri caves', 'Try the local street food at Ram Mandir square'],
    activities: ['Heritage Walk', 'Museum Visit', 'Cave Exploration'],
    budgetMin: 3000,
    budgetMax: 8000,
    contributorName: 'Swagat P.',
    isVerified: true,
  },
  {
    name: 'Banaras Ghats',
    state: 'Uttar Pradesh',
    region: 'North India',
    tag: 'Local Pick',
    emoji: 'River',
    image: '/images/banaras_ghats_1777233756750.png',
    rating: 5.0,
    reviews: 580,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '3-4 days',
    description: 'The spiritual heart of India on the banks of the Ganges, mesmerizing with golden aarti and narrow alleys.',
    tips: ['Take a sunrise boat ride on the Ganges', 'Watch the Ganga Aarti at Dashashwamedh Ghat', 'Try the famous Banarasi Paan'],
    activities: ['Boat Ride', 'Temple Visit', 'Photography', 'Food Tour'],
    budgetMin: 5000,
    budgetMax: 15000,
    contributorName: 'Aditya V.',
    isVerified: true,
  },
  {
    name: 'Ayodhya',
    state: 'Uttar Pradesh',
    region: 'North India',
    tag: 'Hidden Gem',
    emoji: 'Temple',
    image: '/images/ayodhya_1777233779724.png',
    rating: 4.9,
    reviews: 420,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '2-3 days',
    description: 'The birthplace of Lord Ram, boasting majestic stone architecture and a profound sense of devotion.',
    tips: ['Visit Ram Janmabhoomi early', 'Take a stroll along the Sarayu river ghats', 'Watch the evening aarti'],
    activities: ['Temple Visit', 'Heritage Walk', 'Photography'],
    budgetMin: 4000,
    budgetMax: 12000,
    contributorName: 'Sanjay M.',
    isVerified: true,
  },
  {
    name: 'Kerala Backwaters',
    state: 'Kerala',
    region: 'South India',
    tag: 'Local Pick',
    emoji: 'Backwater',
    image: '/images/kerala_backwaters.png',
    rating: 4.9,
    reviews: 370,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '3-5 days',
    description: 'Palm-lined canals, slow houseboat routes, village stops and quiet waterway mornings around Alleppey and Kumarakom.',
    tips: ['Choose a day cruise for tighter budgets', 'Book houseboats with clear meal inclusions', 'Pair backwaters with Fort Kochi or Munnar for a balanced trip'],
    activities: ['Houseboat Cruise', 'Village Walk', 'Seafood Trail', 'Kayaking'],
    budgetMin: 7000,
    budgetMax: 18000,
    contributorName: 'Meera K.',
    isVerified: true,
  },
  {
    name: 'Hampi',
    state: 'Karnataka',
    region: 'South India',
    tag: 'Hidden Gem',
    emoji: 'Ruins',
    image: '/images/hampi_karnataka.png',
    rating: 4.8,
    reviews: 244,
    difficulty: 'Easy-Moderate',
    bestSeason: 'Oct-Mar',
    duration: '2-4 days',
    description: 'A surreal landscape of Vijayanagara ruins, granite boulders, riverside temples and sunset viewpoints.',
    tips: ['Start temple walks early before the heat rises', 'Rent a bicycle or scooter for spread-out ruins', 'Do sunset from Hemakuta Hill or Matanga Hill'],
    activities: ['Heritage Walk', 'Cycling', 'Bouldering', 'Photography'],
    budgetMin: 4500,
    budgetMax: 12000,
    contributorName: 'Arjun R.',
    isVerified: true,
  },
  {
    name: 'Goa Coast',
    state: 'Goa',
    region: 'West India',
    tag: 'Local Pick',
    emoji: 'Coast',
    image: '/images/goa_coast.png',
    rating: 4.7,
    reviews: 510,
    difficulty: 'Easy',
    bestSeason: 'Nov-Feb',
    duration: '3-5 days',
    description: 'Beach villages, Portuguese lanes, seafood shacks and relaxed coastal days across North and South Goa.',
    tips: ['Pick North or South Goa per day instead of crossing repeatedly', 'Book scooters only if you are comfortable riding', 'Keep afternoons light during summer months'],
    activities: ['Beach Hopping', 'Heritage Walk', 'Seafood Trail', 'Water Sports'],
    budgetMin: 6000,
    budgetMax: 20000,
    contributorName: 'Rhea F.',
    isVerified: true,
  },
  {
    name: 'Rann of Kutch',
    state: 'Gujarat',
    region: 'West India',
    tag: 'Offbeat',
    emoji: 'Salt',
    image: '/images/rann_kutch.png',
    rating: 4.8,
    reviews: 186,
    difficulty: 'Easy',
    bestSeason: 'Nov-Feb',
    duration: '2-4 days',
    description: 'A vast white salt desert with craft villages, tent stays, cultural evenings and moonlit winter landscapes.',
    tips: ['Carry warm layers for cold desert nights', 'Visit craft villages around Bhuj for textiles', 'Full moon dates are popular, book stays early'],
    activities: ['Salt Desert Visit', 'Craft Village Tour', 'Cultural Shows', 'Photography'],
    budgetMin: 8000,
    budgetMax: 18000,
    contributorName: 'Nirali P.',
    isVerified: true,
  },
  {
    name: 'Mechuka',
    state: 'Arunachal Pradesh',
    region: 'Northeast',
    tag: 'Remote',
    emoji: 'Valley',
    image: '/images/remote_himalayan_valley.png',
    rating: 4.9,
    reviews: 82,
    difficulty: 'Moderate',
    bestSeason: 'Oct-Mar',
    duration: '4-6 days',
    description: 'A faraway valley near the Indo-Tibet border with wooden monasteries, hanging bridges, river bends and snow-dusted ridges.',
    tips: ['Inner Line Permit is required', 'Keep buffer days for road delays', 'Carry cash for remote villages'],
    activities: ['Monastery Visit', 'River Walks', 'Village Trails', 'Photography'],
    budgetMin: 12000,
    budgetMax: 24000,
    contributorName: 'Tsering L.',
    isVerified: true,
  },
  {
    name: 'Gurudongmar Lake',
    state: 'Sikkim',
    region: 'Northeast',
    tag: 'Remote',
    emoji: 'Lake',
    image: '/images/remote_himalayan_valley.png',
    rating: 4.9,
    reviews: 118,
    difficulty: 'Hard',
    bestSeason: 'Apr-Jun, Oct-Nov',
    duration: '3-5 days',
    description: 'One of India\'s highest lakes, framed by stark Himalayan desert, icy winds and sacred blue water near the Tibetan plateau.',
    tips: ['Acclimatize properly in Lachen', 'Permits are mandatory', 'Avoid if you have altitude issues'],
    activities: ['High-Altitude Drive', 'Photography', 'Monastery Stops', 'Snow Views'],
    budgetMin: 14000,
    budgetMax: 28000,
    contributorName: 'Pema R.',
    isVerified: true,
  },
  {
    name: 'Spiti Valley',
    state: 'Himachal Pradesh',
    region: 'North India',
    tag: 'Remote',
    emoji: 'Desert',
    image: '/images/remote_himalayan_valley.png',
    rating: 4.9,
    reviews: 312,
    difficulty: 'Moderate-Hard',
    bestSeason: 'May-Oct',
    duration: '6-9 days',
    description: 'Cold desert villages, ancient monasteries, moonlike valleys and high passes create one of India\'s most dramatic road journeys.',
    tips: ['Take the Shimla route for gentler acclimatization', 'Fuel up whenever possible', 'Respect monastery timings'],
    activities: ['Road Trip', 'Monastery Visit', 'Stargazing', 'Fossil Village Walks'],
    budgetMin: 18000,
    budgetMax: 35000,
    contributorName: 'Karan B.',
    isVerified: true,
  },
  {
    name: 'Gurez Valley',
    state: 'Jammu & Kashmir',
    region: 'North India',
    tag: 'Hidden Gem',
    emoji: 'River',
    image: '/images/remote_himalayan_valley.png',
    rating: 4.8,
    reviews: 74,
    difficulty: 'Moderate',
    bestSeason: 'May-Oct',
    duration: '3-5 days',
    description: 'A remote Kishanganga river valley with wooden homes, Habba Khatoon peak and alpine quiet far from crowded Kashmir circuits.',
    tips: ['Check road status before leaving Srinagar', 'Carry ID for security checks', 'Stay overnight for sunrise views'],
    activities: ['River Walks', 'Village Trails', 'Peak Views', 'Photography'],
    budgetMin: 10000,
    budgetMax: 22000,
    contributorName: 'Aamir Q.',
    isVerified: true,
  },
  {
    name: 'Agumbe Rainforest',
    state: 'Karnataka',
    region: 'South India',
    tag: 'Remote',
    emoji: 'Rain',
    image: '/images/northeast_rainforest_bridge.png',
    rating: 4.8,
    reviews: 91,
    difficulty: 'Moderate',
    bestSeason: 'Jun-Sep',
    duration: '2-3 days',
    description: 'A rainforest village with mist, waterfalls, rainforest research trails and cinematic monsoon sunsets in India.',
    tips: ['Leech socks help in monsoon', 'Use local guides for forest trails', 'Expect patchy mobile network'],
    activities: ['Waterfalls', 'Rainforest Walks', 'Sunset Point', 'Wildlife'],
    budgetMin: 5000,
    budgetMax: 11000,
    contributorName: 'Ravi H.',
    isVerified: true,
  },
  {
    name: 'Gandikota',
    state: 'Andhra Pradesh',
    region: 'South India',
    tag: 'Offbeat',
    emoji: 'Gorge',
    image: '/images/south_india_canyon.png',
    rating: 4.7,
    reviews: 122,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '1-2 days',
    description: 'India\'s grand canyon, with ochre cliffs, a fort wall and Pennar river views that glow beautifully at sunrise.',
    tips: ['Sunrise is better than midday', 'Pair with Belum Caves', 'Carry water around the gorge'],
    activities: ['Gorge Viewpoints', 'Fort Walk', 'Camping', 'Photography'],
    budgetMin: 3000,
    budgetMax: 8000,
    contributorName: 'Sushma V.',
    isVerified: true,
  },
  {
    name: 'Mawsynram',
    state: 'Meghalaya',
    region: 'Northeast',
    tag: 'Remote',
    emoji: 'Cloud',
    image: '/images/northeast_rainforest_bridge.png',
    rating: 4.8,
    reviews: 104,
    difficulty: 'Moderate',
    bestSeason: 'Oct-Mar',
    duration: '3-4 days',
    description: 'Rain-carved caves, living root bridges, emerald cliffs and cloud drama in one of the wettest landscapes on earth.',
    tips: ['Carry waterproof bags', 'Hire a local guide for caves', 'Road visibility can change quickly'],
    activities: ['Caves', 'Root Bridges', 'Waterfalls', 'Village Walks'],
    budgetMin: 8000,
    budgetMax: 17000,
    contributorName: 'Iamon L.',
    isVerified: true,
  },
  {
    name: 'Majuli Island',
    state: 'Assam',
    region: 'Northeast',
    tag: 'Local Pick',
    emoji: 'Island',
    image: '/images/river_island_village.png',
    rating: 4.7,
    reviews: 137,
    difficulty: 'Easy',
    bestSeason: 'Oct-Mar',
    duration: '2-3 days',
    description: 'A river island of satras, mask-making villages, cycling paths and slow Brahmaputra sunsets.',
    tips: ['Check ferry timings carefully', 'Cycle between satras', 'Stay in a bamboo cottage if available'],
    activities: ['Cycling', 'Cultural Tours', 'River Ferry', 'Mask Making'],
    budgetMin: 4000,
    budgetMax: 10000,
    contributorName: 'Bhaskar G.',
    isVerified: true,
  },
]

const IMAGE_REPLACEMENTS = {
  '/images/media__1777232474677.png': '/images/dzukou_valley.png',
  '/images/media__1777232649189.png': '/images/tirthan_valley.png',
}

const normalizeImagePath = (image) => IMAGE_REPLACEMENTS[image] || image || ''

const formatDestination = (destination) => ({
  id: destination._id?.toString?.() || destination.name,
  name: destination.name,
  state: destination.state,
  region: destination.region,
  tag: destination.tag,
  emoji: destination.emoji,
  image: normalizeImagePath(destination.image),
  rating: destination.rating,
  reviews: destination.reviews,
  difficulty: destination.difficulty,
  bestSeason: destination.bestSeason,
  duration: destination.duration,
  desc: destination.description,
  tips: destination.tips || [],
  activities: destination.activities || [],
  budget: `Rs ${Number(destination.budgetMin || 0).toLocaleString('en-IN')}-Rs ${Number(destination.budgetMax || 0).toLocaleString('en-IN')}`,
  contributor: destination.contributorName || destination.addedBy?.name || 'WonderTravel Team',
  verified: Boolean(destination.isVerified),
})

const filterCatalog = (destinations, { region, tag, search, verified }) => {
  return destinations.filter((destination) => {
    if (region && region !== 'All Regions' && destination.region !== region) return false
    if (tag && tag !== 'All' && destination.tag !== tag) return false
    if (verified === 'true' && !destination.isVerified) return false
    if (search) {
      const query = search.toLowerCase()
      const haystack = `${destination.name} ${destination.state} ${destination.description}`.toLowerCase()
      if (!haystack.includes(query)) return false
    }
    return true
  })
}

module.exports = {
  fallbackDestinations,
  formatDestination,
  filterCatalog,
}
